# -*- coding: utf-8 -*-
"""AF3toAFSUPD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8SL8M-A-O05GJMW8s5f9PbutUpTKbQO
"""

import json
import sys

if len(sys.argv) > 1:
    print("Argument received:", sys.argv[1])
else:
    print("No argument provided.")

with open(sys.argv[1], "r") as file:
    data = json.load(file)

#print(data)

counts = []
seqs = []
for protein in data['sequences']:
  try:
      counts.append(len(protein['protein']['id']))
      seqs.append(protein['protein']['sequence'])
  except:
      continue
      
sequences = []

for i in range(len(seqs)):
  dictionary = {}
  dictionary2 = {}
  dictionary2['sequence'] = seqs[i]
  dictionary2['count'] = counts[i]
  dictionary2['useStructureTemplate'] = True
  dictionary['proteinChain'] = dictionary2
  sequences.append(dictionary)


countslig = []
ligs = []
for protein in data['sequences']:
  try:
      countslig.append(len(protein['ligand']['id']))
      code = protein['ligand']['ccdCodes'][0]
      ligs.append(f"CCD_{code}")
  except:
      continue
print(ligs) 
if len(countslig) > 0:
    for i in range(len(ligs)):
          dictionary = {}
          dictionary2 = {}
          dictionary2['ligand'] = ligs[i]
          dictionary2['count'] = countslig[i]
          dictionary['ligand'] = dictionary2
          sequences.append(dictionary)

AFSdict = {}
AFSdict['name'] = data['name']
AFSdict['modelSeeds'] = ['905129826']
AFSdict['sequences'] = sequences
AFSdict['dialect'] = 'alphafoldserver'
AFSdict['version'] = 1
AFS = [AFSdict]

name = sys.argv[1].split('_data')[0]
name2 = sys.argv[1]
name = name.split('/')
name = name[len(name)-1]
name2 = name2.split(f"/{name}")[0]
print(name)
print(name2)

with open(f"{name2}/fold_{name}_job_request.json", "w") as file:
    json.dump(AFS, file, indent=1)